name: TT Lynn Photography
favicon: null
layout_spectrum: 0.10696577187627554
typography_spectrum: 0.8104482952039689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2011092179454863
  lightness: 0.8455317469779402
  saturation: 0.24338938109576702
  rhythmicContrast: 0.4762026045937091
purpose: []
