name: TT Lynn Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ebc411'
    - '#48bfc7'
    - '#0049b0'
    - '#f664ad'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.4762026045937091
purpose: []
